
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/order?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: SNOW_SERVICE
zk:
  enabled: false
  url: 127.0.0.1:12181
  sessionTimeoutMs: 5000
  connectTimeoutMs: 5000
  baseSleepTimeMs: 1000
  maxRetries: 5
  maxSleepMs: 3000

netty:
  enabled: true
  port: 10288


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.api.grp.entity
  type-handlers-package: com.api.grp.handler
  executor-type: REUSE
  configuration:
    #使用驼峰
    map-underscore-to-camel-case: true
    #缓存可用
    cache-enabled: true

